### ISSUE TITLE
Message "adding or updating 1 ACL rules"

### ISSUE THREAD

**Issue by sganarel** [geekitude/dokuwiki-plugin-userhomepage#10]
Hi,

Everytime I load the first page (/start) - which is a public page - of my wiki, I get the message "Userhomepage: adding or updating 1 ACL rules."
Could tell me how to fix it ? Maybe it's a bug ?

Thanks you.

**Comment by geekitude** [comment]
Hi
Yes, it is a bug :)
I will try to find out what's the problem but you could greatly help with the following instructions because I'm not sure I can reproduce the problem : 
- backup the file conf/acl.auth.php
- go to admin page then ACL administration
- select all ACL rules concerning userhomepage and delete them
- note what message are fired up by userhomepage right after deletion
- send me or paste here the relevant content of acl.auth.php file (before and after the deletion)

Will keep you informed...

**Comment by geekitude** [comment]
Hi

I still haven't been abble to reproduce the bug you have with the plugin.
If you're still interested in a solution, can you please check your issue
on github to send me some informations...

For your question about links to user page, check here
<https://www.dokuwiki.org/plugin:userhomepage#user_links_with_dokuwiki_s_default_template>
.

Simon

2015-05-22 10:07 GMT+02:00 sganarel <notifications@github.com>:

**Comment by geekitude** [comment]
Btw, are you using ACL at all?

**Comment by sganarel** [comment]
Yes I use ACL.
I remove all ACL related to user: then the plugin say "41 ACL update"

But I still have the message "Userhomepage: adding or updating 1 ACL rules." on the top screen when I am not authentified.

Here attached is a screen capture and my acl.auth.php file (I add extension .jpg to upload it...)

![acl auth php](https://cloud.githubusercontent.com/assets/2787919/8392305/8469d94e-1ce6-11e5-9760-01a0f0e20391.jpg)
![2015-06-27 16_00_31-start le wiki](https://cloud.githubusercontent.com/assets/2787919/8392306/903476c6-1ce6-11e5-8ea0-d375f6164258.png)

**Comment by geekitude** [comment]
Didn't get so far that it occured only when not authentified.
I still can't reproduce it though.

However, when not authentified, the plugin shouldn't even try to change any ACL rule. I should be abble to add a fix to work around this fast.

**Comment by geekitude** [comment]
Workaround published. Keep me informed please :)

**Comment by sganarel** [comment]
You fixed it :+1: 

Thanks You for this.

**Comment by geekitude** [comment]
Good news :)
Thanks for the feedback

2015-06-30 17:08 GMT+02:00 sganarel <notifications@github.com>:
