### ISSUE TITLE
TODO: A link to private user namespace when users are connected

### ISSUE THREAD

**Issue by sganarel** [geekitude/dokuwiki-plugin-userhomepage#11]
Is it possible to put an hyperlink behind the name of the connected user (in the top menu bar) to give a quick access for the user's private namespace (to the start page) ?

**Comment by geekitude** [comment]
Hi

This is not an issue.

You will have to manually change your template to add this, sorry but a plugin can't change that on it's own. Here's for example what you can do with Dokuwiki's default template : 
- open lib/tpl/dokuwiki/tpl_header.php file
- replace these lines:
    if (!empty($_SERVER['REMOTE_USER'])) {
        echo '<li class="user">';
        tpl_userinfo(); /* 'Logged in as ...' */
        echo '</li>';
    }
with : 
    if ((tpl_getConf('userhomepageplugin')) and (!plugin_isdisabled('userhomepage')) and (!empty($_SERVER['REMOTE_USER'])) {
        $userhomepageHelper = plugin_load('helper','userhomepage');
        echo $userhomepageHelper->getComplexLoggedInAs();
    } else {
        echo '<li class="user">';
        tpl_userinfo(); /* 'Logged in as ...' */
        echo '</li>';
    }

You can find more helper functions in Helper section of plugin's official webpage.

Hope this helps

**Comment by geekitude** [comment]
Sorry, the code above was pasted from my own template and will not work.
Check this for a working exemple:
https://www.dokuwiki.org/plugin:userhomepage#user_links_with_dokuwiki_s_default_template

**Comment by Klap-in** [comment]
Since the last release usernames can be linked to userprofiles. This link is configurable. I think the event trigger attached to this functionality is useful for this request.

See event: https://www.dokuwiki.org/devel:event:common_user_link
The default config setting: https://www.dokuwiki.org/config:showuseras

**Comment by geekitude** [comment]
Hi

Thanks for pointing to that event, will try to add this soon.
Changed that "issue" to enhancement ;)

**Comment by geekitude** [comment]
Done and successfully tested with quite a few templates
Thanks again for talking about that event :)

**Comment by sganarel** [comment]
Thanks it's perfect :+1:

**Comment by geekitude** [comment]
Thanks for the feedback.
Enjoy ;)
