### ISSUE TITLE
Public Namespace instead of Public Page

### ISSUE THREAD

**Issue by berho** [geekitude/dokuwiki-plugin-userhomepage#17]
Is it possible to use a public user namespace and put the public page in :user:username:start as it works perfect with the private namespace? 

Regards and thanks for the great work!

**Comment by geekitude** [comment]
Hi

While it is technically possible, it would mean a lot of modifications and it would make some things a bit awkward (plugin's strings related to that public namespace would still use the expression "Public Page" for example) so I'm a bit reluctant.

In your example, you suggest ':user:<username>:start' wich is what's currently used for Private Namespaces. What would you use for "Private Namespace" in your case?
My idea is that if your answer is "I don't need/want private namespaces", I think it would be easy to use the private namespaces as public namespaces...

**Comment by berho** [comment]
Hello,
i want to use :private:username for private namespace and :user:username for public namespace.

**Comment by geekitude** [comment]
Done (https://github.com/geekitude/dokuwiki-plugin-userhomepage/commit/f1f64e3456f38229a7f8a4859a0ce0451aa5828f)...

Here's how to do it:
- even if I made some tests, this is BETA, so **backup your wiki**
- update the plugin :) 
- add ':%NAME%:%START%' at the end of 'plugin»userhomepage»public_pages_ns' setting (ie 'user:%NAME%:%START%' or 'public:%NAME%:%START%'). Yes the ':%NAME%:%START%' syntax is mandatory.
- make sure the 'plugin»userhomepage»users_namespace' will not conflict with the namespace used for public ones or ACL will most likely be buggy). To be more specific, first namespace of each setting should be different ('user' and 'public', 'private' and 'user' or 'private' and 'public' will work)

To keep Dokuwiki's user interwiki link feature (author links at end of page or in revisions pages for example), you will have to add a 'dokuwiki/conf/interwiki.local.conf' containing a line like this:
```user      :public:{NAME}:start```
or
```user      :user:{NAME}:start```
depending of your settings ("start" must be equal to the value of Dokuwiki's [start] setting).

**Comment by berho** [comment]
Sorry, don't work. I get
`UserHomePage error #1 ! Make sure Private and Public namespaces are different. Plugin will have no effect untill this is corrected.`
when saving the configuration which is as follow:
__users_namespace:__ `private`
__public_pages_ns:__ `user:%NAME%:%START%`
__dokuwiki/conf/interwiki.local.conf:__ `user :user:{NAME}:start`

**Comment by geekitude** [comment]
Stupid typo, sorry... It's fixed now but can't change date on plugin's page, to update it you'll need to click "Reinstall" button in plugin manager

**Comment by berho** [comment]
Hey, great! Exactly what i want :)
Many thanks!!

One more question: ist it possible to create user home pages only for group members of special (configured) group?

**Comment by geekitude** [comment]
Great :)

For your new question, it should be quite easy but please create a new issue.
