### ISSUE TITLE
Create user home page only for configurable groups

### ISSUE THREAD

**Issue by berho** [geekitude/dokuwiki-plugin-userhomepage#18]
Hello,
is it possible to create user home pages only for group members of special (configured) group? 
I have a closed wiki but only members of a special group should be able to create pages (including user home pages) at all...

Regards,
berho

**Comment by geekitude** [comment]
It don't think it will be a problem to add such an option but might not be abble to work on it before a few days, will keep you informed.

Regards,
Simon

**Comment by geekitude** [comment]
Hi

New version is ready.
Simply update plugin, go to settings and add the groups for wich something has to happen in 'groups_private' and 'groups_public'.

You will have to manually delete previously created public or private pages and corresponding ACL rules that you don't want anymore.

Let me know if everything's fine
PS: nice idea btw ;)

**Comment by berho** [comment]
Excellent! Great job :)
I've tested this with several users in different groups and it works as expected.

**Thanks a lot!**

**Comment by geekitude** [comment]
Thanks for the feedback and I'm glad you like it ;)
Regards,
Simon
