### ISSUE TITLE
More options for username and name

### ISSUE THREAD

**Issue by Knah-Tsaeb** [geekitude/dokuwiki-plugin-userhomepage#28]
Hi,
I would like this result :
Private page => private:user:start (work well a this time)
Public page => public:user_name:start (impossible to configure this)

And bottom link with 'Last modification by User Name' and link to public page.

If you have any idea to make this conf possible ? Thanks for work.

P.S. : je suis une quiche en anglais mais j'essaie, au besoin je peux le faire en français.

**Comment by geekitude** [comment]
Hi and happy new year ;)

Sorry for the late answer.

Having a "Public namespace" like what you're looking for is more than just
a matter of configuration but it would require a lot of work on plugin's
code. On top of that, I'm not sure that it wouldn't break something in
Dowiki's logic at some point as it looks for a simple page (and not a
namespace) for those "showuseras" links.
For these reasons, I will not make such a modification.
Here is something you could try : let Userhomepage create standard public
pages for your users and use Redirect
<https://www.dokuwiki.org/plugin:redirect> or PageRedirect
<https://www.dokuwiki.org/plugin:pageredirect> to redirect them to the
namespaces you would like to use instead (Userhomepage will create
user:admin page wich could be redirected to public:admin:start).

"Last modified by..." link should allready work as intended and point to
correct Userhomepage public page (if you did set DW's "showuseras" to
correct value and enabled Userhomepage's "userlink_replace"). If not, it
might be a bug or a problem with your Template. Let me know wich one you
use and I'll check if there's a compatibility problem.

Best regards


*Salut et bonne année :)*

*Désolé pour la réponse tardive.*

*Avoir un "espace de nom public" comme tu le souhaite est plus qu'une
simple histoire de configuration et demanderai beaucoup de travail au
niveau du code du plugin. Par ailleurs, je ne suis pas certain que cela ne
briserait pas la logique de Dokuwiki quelque part puisqu'il cherche une
page (et pas un espace de nom) pour ces liens "showuseras".*
*Pour ces raisons, je ne ferait pas cette modification.*
*Voici quelque chose à essayer pour obtenir le résultat voulu : laisse
Userhomepage créer les pages publiques et utilise les plugins Redirect
<https://www.dokuwiki.org/plugin:redirect> ou PageRedirect
<https://www.dokuwiki.org/plugin:pageredirect> pour rediriger ces page vers
les espaces de nom que tu souhaites (Userhomepage créerait donc par exemple
la page user:admin qui serait redirigée vers public:admin:start).*

*Les liens "Dernière modification par..." devraient déjà fonctionner et
pointer vers la bonne page publique créée par Userhomepage (si tu as mis la
bonne valeur pour l'option "showuseras" de DW, à savoir [Nom complet de
l'utilisateur en tant que lien interwiki], et activé l'option
"userlink_replace" de Userhomepage). Si ce n'est pas le cas, ça pourrait
être un bug ou un problème avec le Template que tu utilises. Dis moi lequel
tu utilises et je ferais quelques tests pour voir s'il y a un problème de
compatibilité.*

*Bonne continuation*
*PS: pour la suite, on peut poursuivre en français si tu préfères ;)*

2016-12-16 16:11 GMT+01:00 Knah Tsaeb <notifications@github.com>:

**Comment by Knah-Tsaeb** [comment]
No problem we have life and work outside Github ;-)

I have mass work at this time, I look your solution when I can.
I understand your point of view.

Happy new year too.
