### ISSUE TITLE
Uncompatitble with rc Hogfather

### ISSUE THREAD

**Issue by LuckyDrops** [geekitude/dokuwiki-plugin-userhomepage#37]
Since updating to rc3 of Hogfather new users logging in will create a server error 500. 

Removing the plugin solves the issue.

**Comment by LukasHirsch** [comment]
Hey,
I came along some problems, too. New users logging in is not a problem for me, but all the automated ACL settings aren't working anymore. I believe there has been some changes (renaming of functions) in \plugins\acl\admin.php. For example `_acl_del` and `_acl_add` where renamed to `deleteACL` and `addOrUpdateACL`.
I'll try to add the changes, branch it and open a merge request. Maybe this is all what is needed to make the plugin compatible with RC3 Hogfather.
Cheers
Lukas

**Comment by geekitude** [comment]
Hi
@LuckyDrops : sorry for answering that late,, real life was quite eventfull. I'll try to check that issue.
@LukasHirsch : thanks for the hints, a PR would be great if you get things working ;)

**Comment by ebora** [comment]
Isn't this solved?
I had a new user log in for the first time shortly after the update "Renamed ACL functions for Hogfather compatibility" and it worked.
Don't see any other issues either with Hogfather.

**Comment by geekitude** [comment]
Yes it is solved but I wanted to keep issue since I didn't get any feedback from @LuckyDrops.
But I guess he won't give any :(
