### ISSUE TITLE
Copy errors of template when language is not present

### ISSUE THREAD

**Issue by arteteco** [geekitude/dokuwiki-plugin-userhomepage#40]
Hello everyone, I know there is another issue open which may look similar but I think is a different thing.

The error is this:
`Copy error (lib/plugins/userhomepage/lang/it/userhomepage_private.default > ./data/./pages/user/userhomepage_private.txt)`

Also, on the top, I have a php error:

`Warning: copy(lib/plugins/userhomepage/lang/it/userhomepage_private.default): failed to open stream: No such file or directory in /web/htdocs/www.asnuaps.it/home/doku/lib/plugins/userhomepage/action.php on line 366`

I checked via ftp and there is no `it` folder under `lang/`, so I think the problem is a lack of translation. In this case, to avoid the error, I think the plugin should just use the English template.
 
I'm solving the issue by copying the `en` folder and renaming it to `it`

Thanks!

**Comment by geekitude** [comment]
Hi

Thanks for that discover, I will make sure it defaults to english
templates.

Happy new year

**Comment by geekitude** [comment]
Finally fixed that long forgotten issue :blush:
https://github.com/geekitude/dokuwiki-plugin-userhomepage/commit/c27212a697a6a238853ff3dc68dc333c9f36e72c
