### ISSUE TITLE
Redirect to wiki start page

### ISSUE THREAD

**Issue by LukasHirsch** [geekitude/dokuwiki-plugin-userhomepage#43]
Hi,
would it be possible to add an option in the "Configuration Settings" that allows to choose if redirecting to the private page after login is enabled?
In my case each user has its private sidebar from where one can always access the private page, namespace and public page. So after login it would be favorable to not be redirected, but land on the wiki start page.
Maybe there is already an option or way to do this, so I'm sorry if I missed that and would appreaciate your help.
Thanks!

**Comment by geekitude** [comment]
Hello

There's a setting named "redirection" 😅
Disable it and it should do the trick (redirection will still happen on
private page creation though).

Simon

**Comment by LukasHirsch** [comment]
Hi Simon,
I knew there had to be an option, thanks a lot for your quick answer!
Lukas
