### ISSUE TITLE
Add the userpage to the `Last modified by` text

### ISSUE THREAD

**Issue by Gamemap** [geekitude/dokuwiki-plugin-userhomepage#44]
Perhaps this could be included in the documentation. (https://www.dokuwiki.org/plugin:userhomepage#user_links)
This code needs to be included in the `main.php` of the wiki template to add a link at the bottom of the page to the user page of the last editor.

![last_modified](https://user-images.githubusercontent.com/71942164/146280227-69116ad9-bf02-49c6-9e8a-32cc1523bc53.PNG)
----
Old Code:
```html
<div class="docInfo"> <?php tpl_pageinfo() ?></div>
```
New Code:
``` php
<div class="docInfo">
				<?php
                        if (!plugin_isdisabled('userhomepage')) {
							$userhomepageHelper = plugin_load('helper','userhomepage');
						}
						// If User HomePage helper is loaded, replace standard 'Logged in as...' link (case where one or both pages don't exist is managed by User HomePage helper
						if ($userhomepageHelper) {
							$fn = $INFO['filepath'];
							if(!$conf['fullpath']) {
								if($INFO['rev']) {
									$fn = str_replace($conf['olddir'].'/', '', $fn);
								} else {
									$fn = str_replace($conf['datadir'].'/', '', $fn);
								}
							}
							$fn   = utf8_decodeFN($fn);
							$date = dformat($INFO['lastmod']);
							
							if($INFO['exists']) {
								$out = '';
								$out .= '<bdi>'.$fn.'</bdi>';
								$out .= ' · ';
								$out .= $lang['lastmod'];
								$out .= ' ';
								$out .= $date;
								if($INFO['editor']) {
									$out .= ' '.$lang['by'].' ';
									$out .= '<bdi>'.$userhomepageHelper->getAnyPublicLink(editorinfo($INFO['editor'],true)).'</bdi>'; // tpl_pageinfo() mit userhomepage link
								} else {
									$out .= ' ('.$lang['external_edit'].')';
								}
								if($INFO['locked']) {
									$out .= ' · ';
									$out .= $lang['lockedby'];
									$out .= ' ';
									$out .= '<bdi>'.editorinfo($INFO['locked']).'</bdi>';
								}
							}
							echo $out;
						} else {
							tpl_pageinfo();
						}
                    ?>
				</div>
				<!--<div class="docInfo"> <//?php tpl_pageinfo() ?></div> //This is replaced by all above
```

The Code is copied from the function `tpl_pageinfo()` and then modified.
(`$out .= '<bdi>'.$userhomepageHelper->getAnyPublicLink(editorinfo($INFO['editor'],true)).'</bdi>'`)

**Comment by geekitude** [comment]
That's exactly what `getAnyPublicLink` function was made for but I didn't go deep enough :blush:
Thanks for pointing that out 👍 

I will very soon build a new helper function to use in place of `tpl_pageinfo()` rather than adding instructions to documentation.

**Comment by geekitude** [comment]
Fixed (https://github.com/geekitude/dokuwiki-plugin-userhomepage/commit/3f7c6f6d4d20069748761693db5eefe7bb5fa71e)
Added a helper fuction and documentation (https://www.dokuwiki.org/plugin:userhomepage#editor_locker_link) to replace `docInfo` plain text to display link to editor's (or locker's) public page.

**Comment by Gamemap** [comment]
Thank you very much!

**Comment by geekitude** [comment]
You're welcome.
Thanks for your ideas.
