### ISSUE TITLE
Wiki not loading after installing

### ISSUE THREAD

**Issue by oars** [geekitude/dokuwiki-plugin-userhomepage#6]
I added the plugin through the extension manager and somehow nothing loads now. Any suggestions?

**Comment by geekitude** [comment]
Added a test on useacl option today that might solve the problem for Oscar (if it does, I apologize for not seeing that earlier when you sent your options values).

**Comment by geekitude** [comment]
Issue reported as solved by bmolitor (thanks for his patience and contribution).
Keeping issue opened for a few more months just in case.

**Comment by geekitude** [comment]
Closing the issue
