### ISSUE TITLE
Plugin clears acl.auth.php, breaking all ACL rules

### ISSUE THREAD

**Issue by csieber** [geekitude/dokuwiki-plugin-userhomepage#7]
Hello,

since we installed the plugin we oberserved a strange behavior of the Wiki which we were unable to reproduce. On average all 2 weeks, the acl.auth.php is suddenly cleared and only the userhomepage ACL rules are set. This causes the Wiki to complain ("no valid ACL setup") and denying everyone the access to the Wiki.

Our Wiki is set-up on a virtual Ubuntu 14.04 server running on a XenServer. The data and configuration is located on a cifs share on a different Host (a NAS). The Wiki is used on average once a minute.

Dokuwiki Version: Hrun
Plugin Version: 2014-10-26 (not current)

Maybe there is some race condition problem with the code you use to remove duplicate ACL lines and the Wiki storing the ACL requests in combination with a delay on the cifs share connection.

We will deactive the ACL setup as we don't need it. But maybe this description could be helpful in fixing the bug should it occur more often to someone else.

Best regards and thanks for the great plugin,
Christian

**Comment by geekitude** [comment]
Bug was still there. I hope changing writing ACL with file_put_contents() for io_saveFile() will fix it for good.
Will keep issue opened for at least a few months before closing.

**Comment by geekitude** [comment]
Bug occured again a few days ago.
Next guess is that there was way too many operations on acl.auth.php file on each page load (rewrite all rules then delete duplicated lines).
Hopefully fixed by today's version.

**Comment by geekitude** [comment]
It seems that this bug has been fixed by the modification of the ACL process.
Closing the issue
